apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-alpine-deployment
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-alpine
  template:
    metadata:
      labels:
        app: demo-alpine
    spec:
      containers:
        - name: my-alpine-demo-kubernetes
          image: egadoc/myimage:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: demo-service-kube
spec:
  selector:
    app: demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000

